//  RegionPalette.swift
//  Map territory-tint FAMILIES (ws-ios-polish, COMMIT 2).
//
//  T's complaint: the shipping region set (Paul Tol "vibrant", `CorpusPhysicsScene.
//  territoryPaletteHex`) is SATURATED AT MID-LIGHTNESS — the muddiest zone on a dark ground.
//  These families regenerate the 12 region colours from per-appearance OKLCH parameters (was HSL
//  until 2026-09-13) so the whole set can move OUT of the mud, and they are TUNER-DIALABLE (the
//  instrument hands T the parameters; CC does not pick final values — that has misfired twice).
//  ★ OKLCH, not HSL, because HSL "lightness" is not PERCEIVED lightness — see `Params`.
//
//  ★ CURRENT = the shipping hex, verbatim, as the A/B baseline. When the active family is
//    `.current` (the default, and the ONLY reachable family outside DEBUG), resolution is
//    byte-identical to today, so Release is unaffected.
//  ★ PER APPEARANCE: light and dark carry independent params. PASTEL / NEON are dark-FAVOURED
//    (high-lightness colour needs a dark ground to read; on cream it washes out — the same
//    headroom logic that killed the glow on cream). On light they are pushed darker/more
//    saturated = "the best they can do", never silently washed out (see `defaults`).

import UIKit

enum RegionPaletteFamily: Int, CaseIterable {
    case current = 0, subdued, jewel, pastel, neon
    var displayName: String {
        switch self {
        case .current: return "Current"
        case .subdued: return "Subdued"
        case .jewel:   return "Jewel"
        case .pastel:  return "Pastel"
        case .neon:    return "Neon"
        }
    }
    /// Families that are dark-favoured — reported to T; on light they resolve to a darker/more
    /// saturated variant ("best it can do") rather than a washed-out one.
    var darkFavoured: Bool { self == .pastel || self == .neon }
}

enum RegionPalette {
    static let slotCount = 12

    // T device-final 2026-09-15 — Neon, OKLCH-generated, gamut-mapped,
    // hue-locked (hueStart 0.550 / spread 1.000 shared). Do not hand-edit;
    // regenerate via the generator. See Ops/reference/tuner-state-accepted.md
    //
    // The SHIPPING territory palette. Slot i is the SAME HUE in both arrays (verified: worst pair
    // differs by 0.31°, hues evenly spaced 30° from 198°); only lightness differs — OKLCH L ≈ 0.757
    // dark, ≈ 0.603 light. Distinct 12/12 both; CVD D6/P8 dark, D7/P9 light.
    static let currentHexDark: [String] = [
        "#07C8CD", "#07C1F9", "#7DB2FF", "#ACA2FF", "#E283FF", "#FF7CC4",
        "#FF878D", "#FE8E4F", "#E6A100", "#BBB705", "#57D006", "#02CE9D"
    ]
    static let currentHexLight: [String] = [
        "#079397", "#038EB8", "#107AFE", "#815CFF", "#C401EE", "#E1019B",
        "#EF0447", "#CC5B01", "#AA7603", "#898602", "#3E9901", "#029873"
    ]
    /// The CURRENT family's 12 hexes for an appearance — the single source every consumer routes
    /// through (orb tint via `color(isLight:slot:)`, label-pill stroke + node tint via CanvasView).
    static func currentHex(isLight: Bool) -> [String] { isLight ? currentHexLight : currentHexDark }

    /// Family character as OKLCH params (2026-09-13 — was HSL).
    ///
    /// ★ WHY OKLCH. HSL "lightness" is not PERCEIVED lightness: HSL yellow and HSL blue at
    /// L = 0.5 are wildly different brightnesses to the eye. A 12-slot set generated by rotating
    /// hue at fixed HSL L therefore reads UNDESIGNED — some slots pop, some sink, and no amount of
    /// hue rotation fixes it because the axis being held constant isn't the one the eye measures.
    /// OKLCH holds PERCEPTUAL lightness (L) and chroma (C) constant across hue, which is what
    /// designed palettes do. It also matters here specifically: T is colourblind, so LUMINANCE is
    /// the channel he can judge — making it the controlled axis is the point, not a nicety.
    ///
    /// `hueStart`/`hueSpread` are fractions of the hue circle, unchanged in meaning.
    /// `chroma` is a 0…1 DIAL mapped to OKLCH C in 0…`chromaDialMax`; `lightness` is a 0…1 dial
    /// used as OKLCH L directly. ★ Renamed from `sat`/`light` DELIBERATELY: an old HSL value has no
    /// meaning in OKLCH, so the rename makes stale dialed values fail loudly (skipped on import and
    /// listed) instead of being silently reinterpreted into a different colour space.
    ///
    /// These are STARTING POINTS that carry each family's character — T dials the finals on device.
    /// CC does not pick final palette values (that has misfired repeatedly this arc).
    struct Params { var hueStart: Double; var hueSpread: Double; var chroma: Double; var lightness: Double }

    /// Full-scale of the `chroma` dial in OKLCH C. 0.4 is beyond sRGB for every hue, so the top of
    /// the dial is always gamut-limited rather than unreachable — the mapper (below) handles it.
    static let chromaDialMax: Double = 0.4

    static func defaults(_ f: RegionPaletteFamily, isLight: Bool) -> Params {
        switch f {
        case .current:
            return Params(hueStart: 0, hueSpread: 1, chroma: 0, lightness: 0)  // unused — hex path
        case .subdued:   // low chroma, mid L — desaturation is the direct opposite of mud
            return isLight ? Params(hueStart: 0, hueSpread: 1, chroma: 0.22, lightness: 0.55)
                           : Params(hueStart: 0, hueSpread: 1, chroma: 0.24, lightness: 0.68)
        case .jewel:     // high chroma, LOW L — rich; the darkness is intentional
            return isLight ? Params(hueStart: 0, hueSpread: 1, chroma: 0.55, lightness: 0.45)
                           : Params(hueStart: 0, hueSpread: 1, chroma: 0.58, lightness: 0.50)
        case .pastel:    // low chroma, HIGH L — dark-favoured; on light pushed down
            return isLight ? Params(hueStart: 0, hueSpread: 1, chroma: 0.25, lightness: 0.70)
                           : Params(hueStart: 0, hueSpread: 1, chroma: 0.22, lightness: 0.86)
        case .neon:      // high chroma + high L, NARROW hue range — dark-favoured
            return isLight ? Params(hueStart: 0.55, hueSpread: 0.42, chroma: 0.68, lightness: 0.62)
                           : Params(hueStart: 0.55, hueSpread: 0.42, chroma: 0.72, lightness: 0.76)
        }
    }

    // MARK: - Active family + dialled params (DEBUG tuner) — .current everywhere in Release.

    /// Release ships `.current` only. The other families + the OKLCH generator are kept in code
    /// (customisation is a later feature) but nothing can select them — the tuner that did is gone.
    static var activeFamily: RegionPaletteFamily { .current }

    /// Family params, defaults overlaid by the live tuner dials (DEBUG only).
    ///
    /// ★ **HUE IDENTITY IS SHARED ACROSS APPEARANCES** (T ruling, 2026-09-14): the same region must
    /// be the same HUE in both grounds — only lightness and chroma may differ per ground. Dark and
    /// light Neon had been dialled independently (dark started at 0.550 turns, light at 1.000), so a
    /// region CHANGED COLOUR on an appearance flip. `hueStart`/`hueSpread` are therefore stored per
    /// FAMILY only (shared), while `chroma`/`lightness` stay per appearance. The hue DEFAULT is read
    /// from the DARK params because dark is the appearance T has been approving.
    static func params(_ f: RegionPaletteFamily, isLight: Bool) -> Params {
        var p = defaults(f, isLight: isLight)
        let hueDefaults = defaults(f, isLight: false)          // hue identity comes from DARK
        p.hueStart = hueDefaults.hueStart
        p.hueSpread = hueDefaults.hueSpread
        return p
    }

    /// The resolved colour for a territory SLOT (index) in the active family + appearance.
    static func color(isLight: Bool, slot: Int) -> UIColor {
        let fam = activeFamily
        if fam == .current {
            let hex = currentHex(isLight: isLight)
            return UIColor(hex: hex[slot % max(hex.count, 1)]) ?? .gray
        }
        let p = params(fam, isLight: isLight)
        let n = max(slotCount, 1)
        var hue = p.hueStart + p.hueSpread * (Double(slot % n) / Double(n))
        hue -= floor(hue)
        // OKLCH → gamut-mapped sRGB. L and h are held EXACTLY; only C moves if the colour is
        // outside sRGB (see gamutMappedRGB) — so the set keeps one perceived lightness across hue.
        let (r, g, b) = gamutMappedRGB(l: clamp01(p.lightness),
                                       c: clamp01(p.chroma) * chromaDialMax,
                                       hueTurns: hue)
        return UIColor(red: r, green: g, blue: b, alpha: 1)
    }

    /// The active family + appearance as 12 hex strings — for the tuner's Copy export.
    static func resolvedHex(isLight: Bool) -> [String] {
        (0..<slotCount).map { hexString(color(isLight: isLight, slot: $0)) }
    }

    // MARK: - Distinguishability

    /// The three distinctness readings for a family + appearance.
    struct DistinctCounts { var normal: Int; var deutan: Int; var protan: Int }

    /// How many of the 12 slots stay mutually DISTINCT (min pairwise CIE76 ΔE ≥ `threshold`) —
    /// for NORMAL vision and under deuteranopia / protanopia simulation.
    ///
    /// ★ Why CVD is counted too: the old reading was normal-vision ΔE by its own admission, which
    /// is the wrong test for this app — T is colourblind, and so is ~8% of the male population.
    /// A family that only separates for a normal-vision reviewer fails the actual users. The
    /// constraint ("a dozen+ regions must be tellable apart") has to hold under simulation.
    /// Simulation is Machado et al. 2009 at severity 1.0, applied in LINEAR RGB (the space the
    /// matrices are defined in), then converted to Lab for the same greedy ΔE count.
    static func distinctCounts(_ f: RegionPaletteFamily, isLight: Bool, threshold: Double = 12) -> DistinctCounts {
        var linear: [(Double, Double, Double)] = []
        linear.reserveCapacity(slotCount)
        for s in 0..<slotCount {
            let c = color(isLight: isLight, slot: s)
            var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
            c.getRed(&r, green: &g, blue: &b, alpha: &a)
            linear.append((srgbToLinear(Double(r)), srgbToLinear(Double(g)), srgbToLinear(Double(b))))
        }
        func count(_ transform: ((Double, Double, Double)) -> (Double, Double, Double)) -> Int {
            // Greedily keep slots whose ΔE to every already-kept slot is ≥ threshold.
            var kept: [(Double, Double, Double)] = []
            for c in linear {
                let lab = labFromLinear(transform(c))
                if kept.allSatisfy({ deltaE($0, lab) >= threshold }) { kept.append(lab) }
            }
            return kept.count
        }
        return DistinctCounts(normal: count { $0 },
                              deutan: count(simulateDeutan),
                              protan: count(simulateProtan))
    }

    /// Normal-vision count (unchanged behaviour/signature — callers that only want the headline).
    static func distinctSlotCount(_ f: RegionPaletteFamily, isLight: Bool, threshold: Double = 12) -> Int {
        distinctCounts(f, isLight: isLight, threshold: threshold).normal
    }

    // MARK: - CVD simulation (Machado et al. 2009, severity 1.0) — LINEAR RGB in, linear RGB out.

    private static func simulateDeutan(_ c: (Double, Double, Double)) -> (Double, Double, Double) {
        ( 0.367322 * c.0 + 0.860646 * c.1 - 0.227968 * c.2,
          0.280085 * c.0 + 0.672501 * c.1 + 0.047413 * c.2,
         -0.011820 * c.0 + 0.042940 * c.1 + 0.968881 * c.2)
    }

    private static func simulateProtan(_ c: (Double, Double, Double)) -> (Double, Double, Double) {
        ( 0.152286 * c.0 + 1.052583 * c.1 - 0.204868 * c.2,
          0.114503 * c.0 + 0.786281 * c.1 + 0.099216 * c.2,
         -0.003882 * c.0 - 0.048116 * c.1 + 1.051998 * c.2)
    }

    // MARK: - Colour maths — sRGB ↔ linear ↔ OKLab ↔ OKLCH (Ottosson), plus Lab/ΔE for distinctness.

    static func srgbToLinear(_ v: Double) -> Double {
        v > 0.04045 ? pow((v + 0.055) / 1.055, 2.4) : v / 12.92
    }
    static func linearToSrgb(_ v: Double) -> Double {
        v > 0.0031308 ? 1.055 * pow(v, 1 / 2.4) - 0.055 : 12.92 * v
    }

    /// OKLCH → LINEAR sRGB (may fall outside [0,1] — that's what the gamut mapper tests).
    static func oklchToLinearRGB(l: Double, c: Double, hueTurns: Double) -> (Double, Double, Double) {
        let h = hueTurns * 2 * Double.pi
        let a = c * cos(h), bb = c * sin(h)
        let l_ = l + 0.3963377774 * a + 0.2158037573 * bb
        let m_ = l - 0.1055613458 * a - 0.0638541728 * bb
        let s_ = l - 0.0894841775 * a - 1.2914855480 * bb
        let L = l_ * l_ * l_, M = m_ * m_ * m_, S = s_ * s_ * s_
        return ( 4.0767416621 * L - 3.3077115913 * M + 0.2309699292 * S,
                -1.2684380046 * L + 2.6097574011 * M - 0.3413193965 * S,
                -0.0041960863 * L - 0.7034186147 * M + 1.7076147010 * S)
    }

    /// OKLCH → sRGB, GAMUT-MAPPED BY CHROMA REDUCTION.
    ///
    /// ★ Never clamp the RGB channels: clipping a too-saturated colour shifts BOTH its hue and its
    /// apparent lightness (the channel that clips is the one carrying the hue), which would
    /// reintroduce the exact "slots sit at different brightnesses" problem OKLCH is here to remove.
    /// Instead hold L and h EXACTLY and binary-search C down until the colour is representable.
    /// Consequence worth knowing: for hues sRGB can't hold at the dialed chroma (yellow at low L,
    /// say) the result is LESS chromatic than its neighbours — but still the same lightness. That's
    /// the correct trade; lightness is the axis the eye (and a colourblind eye especially) reads.
    static func gamutMappedRGB(l: Double, c: Double, hueTurns: Double) -> (Double, Double, Double) {
        func inGamut(_ rgb: (Double, Double, Double)) -> Bool {
            let e = 1e-6
            return rgb.0 >= -e && rgb.0 <= 1 + e && rgb.1 >= -e && rgb.1 <= 1 + e && rgb.2 >= -e && rgb.2 <= 1 + e
        }
        var rgb = oklchToLinearRGB(l: l, c: c, hueTurns: hueTurns)
        if !inGamut(rgb) {
            var lo = 0.0, hi = c
            for _ in 0..<8 {                       // ~8 halvings ≈ C to within 0.4/256
                let mid = (lo + hi) / 2
                if inGamut(oklchToLinearRGB(l: l, c: mid, hueTurns: hueTurns)) { lo = mid } else { hi = mid }
            }
            rgb = oklchToLinearRGB(l: l, c: lo, hueTurns: hueTurns)
        }
        // Only a sub-ulp residue can remain after the search; clamp01 here is a safety net, not the
        // gamut strategy.
        return (clamp01(linearToSrgb(rgb.0)), clamp01(linearToSrgb(rgb.1)), clamp01(linearToSrgb(rgb.2)))
    }

    private static func clamp01(_ v: Double) -> Double { min(1, max(0, v)) }

    private static func hexString(_ c: UIColor) -> String {
        var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
        c.getRed(&r, green: &g, blue: &b, alpha: &a)
        return String(format: "#%02X%02X%02X", Int((r * 255).rounded()), Int((g * 255).rounded()), Int((b * 255).rounded()))
    }

    private static func rgbToLab(_ r: Double, _ g: Double, _ b: Double) -> (Double, Double, Double) {
        labFromLinear((srgbToLinear(r), srgbToLinear(g), srgbToLinear(b)))
    }

    /// CIE-Lab from LINEAR sRGB — the entry point the CVD path needs (its matrices operate in
    /// linear RGB, so re-encoding to sRGB just to decode again would be lossy noise).
    private static func labFromLinear(_ c: (Double, Double, Double)) -> (Double, Double, Double) {
        let R = clamp01(c.0), G = clamp01(c.1), B = clamp01(c.2)
        let x = (R * 0.4124 + G * 0.3576 + B * 0.1805) / 0.95047
        let y = (R * 0.2126 + G * 0.7152 + B * 0.0722)
        let z = (R * 0.0193 + G * 0.1192 + B * 0.9505) / 1.08883
        func f(_ t: Double) -> Double { t > 0.008856 ? pow(t, 1.0 / 3.0) : 7.787 * t + 16.0 / 116.0 }
        let fx = f(x), fy = f(y), fz = f(z)
        return (116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz))
    }

    private static func deltaE(_ a: (Double, Double, Double), _ b: (Double, Double, Double)) -> Double {
        let dl = a.0 - b.0, da = a.1 - b.1, db = a.2 - b.2
        return (dl * dl + da * da + db * db).squareRoot()
    }
}
